version: '3.8'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'RockPaperScissors'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin1'
      MYSQL_ROOT_PASSWORD: 'root11'
    ports:
      - 3306:3306
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      timeout: 20s
      retries: 10

networks:
 my-network:
volumes:
 mysql_data: